workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    environment:
      node: latest
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials   # 🔑 group where certs & provisioning live
    scripts:
      - name: Install Node.js dependencies
        script: npm install
  
      - name: Build web app
        script: npm run build
  
      - name: Sync with Capacitor
        script: npx cap sync ios
  
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
  
      - name: Set up code signing
        script: |
          echo $CM_CERTIFICATE | base64 --decode > certificate.p12
          echo $CM_PROVISIONING_PROFILE | base64 --decode > profile.mobileprovision
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k ~/Library/Keychains/build.keychain -P "$CM_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/Library/Keychains/build.keychain
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
  
      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $CM_BUILD_DIR/App.xcarchive \
                     DEVELOPMENT_TEAM=526K7MWR7Y \
                     archive
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/App.xcarchive \
                     -exportOptionsPlist ios/App/ExportOptions.plist \
                     -exportPath $CM_BUILD_DIR
  
    artifacts:
      - $CM_BUILD_DIR/*.ipa
  
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
  